version: '3.8'

services:
  database:
    container_name: mdhsymfonydatabase
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: mdhsymfony
      MYSQL_USER: mdhsymfony
      MYSQL_PASSWORD: Password123
    ports:
      - '4706:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: mdhsymfonyphp
    build:
      context: ./
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
    container_name: mdhsymfonynginx
    image: nginx:stable-alpine
    ports:
      - '9080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

