version: '3.8'

services:
  database:
    container_name: wk7database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Hunter2
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony_web
      MYSQL_PASSWORD: Hunter2
    ports:
      - '4706:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: wk7php
    build:
      context: ./
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
    container_name: wk7nginx
    image: nginx:stable-alpine
    ports:
      - '9080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

