version: '3'

services:
  symphony-prac-db:
    image: mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3311:3306"
    volumes:
      - symfony-example-data:/var/lib/mysql

  php-fpm-prac:
    build:
      context: ./docker/php-fpm
    depends_on:
      - symphony-prac-db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=24e17c47430bd2044a61c131c1cf6990
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
      ports:
        - '9992:9000'
      volumes:
      - ./src:/var/www

  nginx-prac:
    build:
      context: ./docker/nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm-prac
    ports:
      - "8888:80"
    links:
      - php
    volumes_from:
        - php
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached

volumes:
  symfony-example-data:
