version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3311:3306"
    volumes:
      - symfony-example-data:/var/lib/mysql

  app:
    build:
      context: ./docker/php-apache
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=24e17c47430bd2044a61c131c1cf6990
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3311/${DATABASE_NAME}?serverVersion=5.7
    ports:
      - 84:80
    volumes:
      - ./public:/var/www/html/

volumes:
  symfony-example-data:
