version: "3" # ECS only supports yaml version up to 3. Not 3.1, 3.2, etc

services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: symfony
      MYSQL_USER: test
      MYSQL_PASSWORD: Password123
    ports:
      - "3311:3306"
    volumes:
      - symfony-example-data:/var/lib/mysql

  php-fpm:
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=dev
      - APP_SECRET=24e17c47430bd2044a61c131c1cf6990
      - DATABASE_URL="mysql://test:Password123@127.0.0.1:3311/symfony?serverVersion=5.7"
    ports:
      - '9992:9000'
    volumes:
      - .:/var/www

  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - php-fpm
    ports:
      - "8888:80"
    links:
      - php-fpm
    volumes_from:
      - php-fpm
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./logs/nginx/:/var/log/nginx:cached

volumes:
  symfony-example-data:
